# Generated by Django 3.0.4 on 2020-04-08 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200408_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
