# Generated by Django 3.0.4 on 2020-04-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_orderupdate_timestamp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp1',
        ),
    ]
