# Generated by Django 3.0.4 on 2020-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200408_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='13:08:37', verbose_name='Time'),
        ),
    ]
