# Generated by Django 3.0.4 on 2020-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orderupdate_timestamp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='18:48:32', verbose_name='Time'),
        ),
    ]
