# Generated by Django 3.0.4 on 2020-04-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200408_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='23:02:21', verbose_name='Time'),
        ),
    ]
