# Generated by Django 3.0.4 on 2020-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200409_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='23:08:00', verbose_name='Time'),
        ),
    ]
