# Generated by Django 3.0.4 on 2020-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200409_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='17:03:53', verbose_name='Time'),
        ),
    ]
