# Generated by Django 3.0.4 on 2020-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200410_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='17:04:31', verbose_name='Time'),
        ),
    ]
