# Generated by Django 3.0.4 on 2020-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200410_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp1',
            field=models.TimeField(default='', verbose_name='Time'),
        ),
    ]
